locators = {
        "startApplicationBtn":'//*[@id="customerIDRow"]/div[2]/div[1]/div[2]/a',
        "branchList":'//*[@id="mdcBranch"]/div[1]',
        "creditProgramChoice":'creditProgram2',
        "customerTypeChoice":'customerType1',
        "customerTypeChoice":'customerType1',
        "consentCheckboxChoice":'cbxConsent',
        "firstNameField":'firstCustomerName',
        "lastNameField":'lastCustomerName',
        "idTypeList":'//*[@id="mdcCusIdType"]/div[1]',
        "idTypeChoice":'[data-value="SS"]',
        "idNumberField":'//*[@id="customerIdNum"]',
        "birthDateField":'customerDob',
        "sexList":'//*[@id="mdcCustomerSex"]/div[1]',
        "sexChoice":'[data-value="M"]',
        "mobileNoField":'mobileNumber',
        "emailField":'email',
        "otpField":'/html/body/div/h3',
        "salutationList":'//*[@id="UDF_SSP_CUST_INDIVIDUAL_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_SALUTATION"]',
        "civilStatusList":'//*[@id="UDF_SSP_CUST_INDIVIDUAL_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_CIVIL_STATUS"]',
        "pobProvinceList":'//*[@id="UDF_SSP_CUST_INDIVIDUAL_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_POB_PROVINCE"]',
        'pobCityList':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_POB_CITY"]',
        "tinField":'//*[@id="UDF_SSP_CUST_INDIVIDUAL_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_TIN"]',
        'governmentIDTypeList':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_GOVT_ID_TYPE"]',
        'govermentIDTypeField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_GOVT_ID_NUMBER"]',
        'spouseFirstNameField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_SPOUSE_DETAILS_SSP_CUST_INDIVIDUAL_SPOUSE_FIRST_NAME"]',
        'spouseLastNameField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_SPOUSE_DETAILS_SSP_CUST_INDIVIDUAL_SPOUSE_LAST_NAME"]',
        'spouseDob':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_SPOUSE_DETAILS_SSP_CUST_INDIVIDUAL_SPOUSE_DOB"]',
        'spouseEmail':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_SPOUSE_DETAILS_SSP_CUST_INDIVIDUAL_SPOUSE_EMAIL_ADDRESS"]',
        'motherFirstNameField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_MOTHER_MAIDEN_NAME_SSP_CUST_INDIVIDUAL_MDN_FIRST_NAME"]',
        'motherLastNameField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_MOTHER_MAIDEN_NAME_SSP_CUST_INDIVIDUAL_MDN_LAST_NAME"]',
        'provinceList':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_HOME_ADDRESS_SSP_CUST_INDIVIDUAL_RESIDENTIAL_ADDRESS_PROVINCE"]',
        'cityList':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_HOME_ADDRESS_SSP_CUST_INDIVIDUAL_RESIDENTIAL_ADDRESS_CITY"]',
        'homeOwnershipButton':'//*[@id="tbody_UDFBlock_SSP_CUST_INDIVIDUAL_HOME_ADDRESS"]/tr[5]/td[2]/span[2]/div/label',
        'businessNameField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_BIZ_BUSINESS_NAME"]',
        'yearBusinessField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_BIZ_OPERATION_YEARS"]',
        'socialMediaField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_BIZ_MEDIA"]',
        'natureBusinessList':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_BIZ_NATURE_OF_BUSINESS"]',
        'specifyBusinessList':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_GENERAL_PROFILE_SSP_CUST_INDIVIDUAL_BIZ_BUSINESS_ACTIVITIES"]',
        'similarhomeAddressButton':'//*[@id="tbody_UDFBlock_SSP_CUST_INDIVIDUAL_BIZ_PRINCIPAL_BUSINESS_ADDRESS"]/tr[1]/td[2]/span[1]/div/label',
        'businessaddressOwnership':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_PRINCIPAL_BUSINESS_ADDRESS_SSP_CUST_INDIVIDUAL_BIZ_ADDR_OWNERSHIP"]',
        'businessRegistrationList':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_REGISTRATION_DETAILS_SSP_CUST_INDIVIDUAL_BIZ_BUSINESS_REGISTRATION0"]',
        'businessRegistrationOthers':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_REGISTRATION_DETAILS_SSP_CUST_INDIVIDUAL_BIZ_BUSINESS_REGISTRATION_OTHERS0"]',
        'dateRegistrationField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_REGISTRATION_DETAILS_SSP_CUST_INDIVIDUAL_BIZ_BUSINESS_REGISTRATION_DATE0"]',
        'expiryRegistrationField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_REGISTRATION_DETAILS_SSP_CUST_INDIVIDUAL_BIZ_BUSINESS_EXPIRY_DATE0"]',
        'registrationNumberField':'//*[@id="UDF_SSP_CUST_INDIVIDUAL_BIZ_REGISTRATION_DETAILS_SSP_CUST_INDIVIDUAL_BIZ_BUSINESS_REGISTRATION_NO0"]',
        'firmSizeButton':'//*[@id="tbody_UDFBlock_SSP_CUST_INDIVIDUAL_BIZ_FIRM_SIZE_EMPLOYMENT_DETAILS"]/tr[1]/td[2]/span[2]/div/label',
        'repaymentofLoans':'//*[@id="available_UDF_SSP_CUST_INDIVIDUAL_SOURCE_OF_FUNDS_SSP_CUST_INDIVIDUAL_SOURCE_OF_FUNDS_REPAYMENT"]/option[1]',
        'addROLButton':'//*[@id="addBtn_UDF_SSP_CUST_INDIVIDUAL_SOURCE_OF_FUNDS_SSP_CUST_INDIVIDUAL_SOURCE_OF_FUNDS_REPAYMENT"]',
        'loanAmountField':'//*[@id="UDF_SSP_CUST_LOAN_APPLICATION_INFO_SSP_CUST_LOAN_APPLICATION_LOAN_AMOUNT"]',
        'tenorField':'//*[@id="UDF_SSP_CUST_LOAN_APPLICATION_INFO_SSP_CUST_LOAN_APPLICATION_LOAN_TENOR"]',
        'proposedRepaymentList':'//*[@id="UDF_SSP_CUST_LOAN_APPLICATION_INFO_SSP_CUST_LOAN_APPLICATION_LOAN_REPAYMENT_FREQUENCY"]',
        'loanFacilityList':'//*[@id="UDF_SSP_CUST_LOAN_APPLICATION_INFO_SSP_CUST_LOAN_APPLICATION_LOAN_FACILITY"]',
        'loanPurposeList':'//*[@id="available_UDF_SSP_CUST_LOAN_APPLICATION_INFO_SSP_CUST_LOAN_APPLICATION_LOAN_PURPOSE"]/option[2]',
        'addloanPurposeButton':'//*[@id="addBtn_UDF_SSP_CUST_LOAN_APPLICATION_INFO_SSP_CUST_LOAN_APPLICATION_LOAN_PURPOSE"]',
        'typeofLoanButton':'//*[@id="udf_table_SSP_CUST_LOAN_APPLICATION_INFO"]/tbody/tr[4]/td[2]/span[2]/div/label',
        'documentChecklist':'//*[@id="documentChecklistLegend"]',
        'attachmentNameField':'documentName',
        'fileUploadButton':'fileUpload',
        'saveButton':'//*[@id="udfSection"]/table[2]/tbody/tr/td/table/tbody/tr[2]/td[2]/a',
        'okayButton':'/html/body/div[13]/div/div[6]/button[1]',
        'previewButton':'//*[@id="udfSection"]/table[2]/tbody/tr/td/table/tbody/tr[2]/td[3]/a',
        'submitButton':'//*[@id="proceedButton"]',
        'showESGButton':'//*[@id="loadingDiv"]/div/div[1]/div[2]/div/a',
        'submitESGButton':'//*[@id="content-body"]/form/table[4]/tbody/tr/td/table/tbody/tr[2]/td/a',
        'ESGquestionnaire':'//*[@id="content-body"]/form/table[2]/tbody/tr[1]/td/h3/input',
        'userName':'//*[@id="userName"]',
        'password':'password',
        'signInButton':'//*[@id="btn_signin"]',
        'firstTimeLoginButton':'//*[@id="btn_first_time_login"]',
        'firstTimeLoginIDType':'//*[@id="idType"]',
        'firstTimeLoginIDNumber':'//*[@id="idNumber"]',
        'firstTimeLoginLoginID':'//*[@id="loginID"]',
        'nextButton':'//*[@id="forgotPwdDiv"]/div[4]/a[2]',
        'newPassword':'newPassword',
        'confirmPassword':'confirmPassword',
        'submitPassword':'//*[@id="changePwdDiv"]/div[4]/a[2]',
        'goToLogin':'//*[@id="ackMessageDiv"]/div[3]/a',
        'applicationDetails':'//*[@id="listingTable"]/table/tbody/tr/td[3]/a',
        'appListing':'//*[@id="customer_data"]/div[1]/p/span[1]'
}

branches = {
        "ANTIQUE-T.A. FORNIER":'//*[@id="branchList"]/li[21]',
        "CEBU BUSINESS PARK":'//*[@id="branchList"]/li[152]',
        "GREENHILLS-CLUB FILIPINO DRIVE":'//*[@id="branchList"]/li[244]',
        "GREENHILLS-ORTIGAS AVE.":'//*[@id="branchList"]/li[245]',
        "HEAD OFFICE CENTER":'//*[@id="branchList"]/li[246]',
        "MAKATI-ALLIED BANK CENTER":'//*[@id="branchList"]/li[332]/span[2]',
        'MAKATI-AGUIRRE':'//*[@id="branchList"]/li[331]/span[2]',
        'MAKATI-AMORSOLO':'//*[@id="branchList"]/li[333]/span[2]',
        'BGC 7TH AVENUE':'//*[@id="branchList"]/li[62]',
        'BGC ONE MCKINLEY PLACE':'//*[@id="branchList"]/li[63]'
}

application_types = {
        "New Application": '//*[@id="udf_table_SSP_CUST_CUSTOMER_TYPES"]/tbody/tr[1]/td[4]/span[1]/div/label'
}

iframes = {
    "sblaf_main_iframe":"productDetailsFrame",
    "upload_document_iframe":"//iframe[contains(@class, 'fancybox-iframe')]"
}





